export type Product = {
  name: string
  slug: string
  img: string
  images?: string[]
  videos?: (string | null)[]
  cat: 'kuechen' | 'schraenke' | 'baeder'
  type: string
  label: string
}

export const CAT_URL: Record<string, string> = {
  kuechen: 'kuechen',
  schraenke: 'schraenke',
  baeder: 'baeder',
}

export const PRODUCTS: Product[] = [
  // ── Küchen · Modern (kuhnimilana) ────────────────────────────────
  { name: 'Grafis',        slug: 'grafis',        cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/07pxOyAzMM8LAKQhj_P1p1s.jpg',
    images: [
      '/images/products/07pxOyAzMM8LAKQhj_P1p1s.jpg',
      '/images/products/0inf0eZjq9vaH2cmA_pZDlb.jpg',
      '/images/products/0sVGUq1zdKqpIvx0E_cEPjn.jpg',
      '/images/products/0Dq6djgvGQ47gNn7E_XKby1.jpg',
      '/images/products/05StiwvLV5lZ2NBOa_fBvCw.jpg',
      '/images/products/0G64ypiHxd7dC8yx8_PoRAd.jpg',
      '/images/products/01otTiimDoE10ulNg_j20gC.jpg',
      '/images/products/0iOw6GhF1AgLtagdl_fZBDV.jpg',
    ],
    videos: ['/videos/products/Графис__93pct_smaller.mp4', null, null, null, null, null, null, null],
  },
  { name: 'Granby',        slug: 'granby',        cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/0cZ3AVTlSyxPUwLgW_fAZRl.jpg',
    images: [
      '/images/products/0cZ3AVTlSyxPUwLgW_fAZRl.jpg',
      '/images/products/04PgbGC2Y0hQFGGnD_AqQD0.jpg',
      '/images/products/0pbEuxLBCeovCt1KW_Q7xPM.jpg',
      '/images/products/0Ezj1sQOCnRvwEX4O_Mb7hw.jpg',
      '/images/products/0GBQ4bBYtBzXJkIq9_FlXgK.jpg',
      '/images/products/0nuOZBdQhDqqgURFe_57t0o.jpg',
      '/images/products/0orIneKVbMTPezMJh_Uq9Gl.jpg',
      '/images/products/01OPx1AtpeFl9LuH5_leZZA.jpg',
      '/images/products/0eLBFFmuxVN0VbwDi_DeFWk.jpg',
      '/images/products/0Ijp7IMdw4eobSkyj_kg2fW.jpg',
      '/images/products/0NhYb24Hrhw9JSenc_cMCOF.jpg',
      '/images/products/0Qng2z1PDHWlZMuan_bpUCj.jpg',
      '/images/products/0ktuahH6W6cjbKHYc_Y3qVv.jpg',
      '/images/products/0mvTpr8vqXDbmfbVu_a7Ibt.jpg',
    ],
    videos: ['/videos/products/Гранби3__92pct_smaller.mp4', null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  { name: 'Budbin',        slug: 'budbin',        cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/0jifM8SdyZJQgxzHv_flxWI.jpg',
    images: [
      '/images/products/0jifM8SdyZJQgxzHv_flxWI.jpg',
      '/images/products/0yeIHaM1UKb5k81aD_nShcX.jpg',
      '/images/products/0UIUgObC2HfprzXhE_CP4o5.jpg',
      '/images/products/0TO1dM58rr2gfVt4g_6YfjW.jpg',
      '/images/products/0I7IgL4A0D0vTYI6B_h2QUK.jpg',
      '/images/products/09ppwlqQ3bqG6FPwZ_Mtt8x.jpg',
      '/images/products/08ZtrRMLF9s0cTMgW_syIqL.jpg',
      '/images/products/0V7C0tBS6mAq2nzDR_OhwQC.jpg',
      '/images/products/0C6bZZg4YZair8SC1_G9PF4.jpg',
    ],
    videos: ['/videos/products/Будбин__93pct_smaller.mp4', null, null, null, null, null, null, null, null],
  },
  { name: 'Kolaria',       slug: 'kolaria',       cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/0kesx1Y2Pt92wkDDx_04Vkl.jpg',
    images: [
      '/images/products/0kesx1Y2Pt92wkDDx_04Vkl.jpg',
      '/images/products/09NhXpu98iGJEySEn_65TT4.jpg',
      '/images/products/0clor9XYx7kFblogY_4mJKE.jpg',
      '/images/products/0VOgYBZv53tBUyVOl_c4r80.jpg',
      '/images/products/0pWdToX8vT3ltw80U_Sz1UA.jpg',
      '/images/products/0dFQdEndDqWCjB2NW_OhScL.jpg',
      '/images/products/0jHz23YKDu0ja1JpC_qxKoh.jpg',
      '/images/products/0AeIRvirCbXC1ARDw_swDfA.jpg',
    ],
    videos: ['/videos/products/Колария__92pct_smaller.mp4', null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  { name: 'Roshedu',       slug: 'roshedu',       cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/097K8FXmtcZoVqJVy_lu4a1.jpg',
    images: [
      '/images/products/097K8FXmtcZoVqJVy_lu4a1.jpg',
      '/images/products/01fzODmKRtoACKIqP_SNR4S.jpg',
      '/images/products/09OlMNCCasbZch57a_8y4Tn.jpg',
      '/images/products/0iGPVbebDtfvbxgis_cvQhd.jpg',
    ],
    videos: ['/videos/products/Рошеду__84pct_smaller.mp4', null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  { name: 'Brix',          slug: 'brix',          cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/0q9jxltANXHL3RmIm_2b9zJ.jpg',
    images: [
      '/images/products/0q9jxltANXHL3RmIm_2b9zJ.jpg',
      '/images/products/0W9N0f0UQtUU8gzyp_ilHCG.jpg',
      '/images/products/0MuLYk4SKIfE4KkRu_8rbGV.jpg',
      '/images/products/0LUDDn6fLhRnK9uEb_GNT29.jpg',
      '/images/products/0pkfH4Y3p5qHWwlSK_VlmLA.jpg',
      '/images/products/07Dc1P8WPyZo4XYVc_Z14Mc.jpg',
      '/images/products/03JjXt5HmY7CmoP0q_z3GbB.jpg',
      '/images/products/04ApgWkdJeTRkCapV_t7hm7.jpg',
    ],
    videos: ['/videos/products/Брикс__92pct_smaller.mp4', null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  { name: 'Sadbury',       slug: 'sadbury',       cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/05iefZ2FsYxLSnvb3_z5ytb.jpg',
    images: [
      '/images/products/05iefZ2FsYxLSnvb3_z5ytb.jpg',
      '/images/products/0xSU8DworoUoBaeLz_Njvgd.jpg',
      '/images/products/0ofRZONTSmNn3QwzH_3Sgne.jpg',
      '/images/products/0he2FsiD1HMO1uMYB_b0Cww.jpg',
      '/images/products/0fSyQsV6EYWwSlOeF_vW3jM.jpg',
      '/images/products/0E52BUKkHIltpq4ZJ_s7hZG.jpg',
      '/images/products/0Nx3zzLEestMoFO4f_ke8OU.jpg',
    ],
    videos: ['/videos/products/Садбери__90pct_smaller.mp4', null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  { name: 'Tavira',        slug: 'tavira',        cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/04BaGWDW2glkI84IO_Yjrjl.jpg',
    images: [
      '/images/products/04BaGWDW2glkI84IO_Yjrjl.jpg',
      '/images/products/0j0BVzfwIHhDedTDv_jUGrA.jpg',
      '/images/products/0UhFGjNG9j9AcJBn6_Y661B.jpg',
      '/images/products/0mQw7XjFbMX4LaHKG_zklZ1.jpg',
      '/images/products/0sBMKFCloySpvrCx5_km4kP.jpg',
      '/images/products/0mPV8F0q9gt1RzDzy_GrYGR.jpg',
      '/images/products/0UgwSlwaRofYpxHAJ_7GubE.jpg',
      '/images/products/05B1JDuvw82r08PxD_eo68Z.jpg',
      '/images/products/0e4wLtNG12itlm5JA_2RBn1.jpg',
      '/images/products/0cuFB3sBEFhvyjfbz_DLzY9.jpg',
      '/images/products/0PChuGAD6zgU8oGA1_HYYk8.jpg',
      '/images/products/0jzAr9vqA5tdz58aG_BfLLV.jpg',
      '/images/products/0F4ftbpigC8OAlPaD_BKCJu.jpg',
      '/images/products/0AbpdiQ3j7Vkh7jU7_iloLe.jpg',
    ],
    videos: ['/videos/products/Тавира__90pct_smaller.mp4', null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  { name: 'Richmond',      slug: 'richmond',      cat: 'kuechen', type: 'modern', label: 'Küche',
    img: '/images/products/0LSLx8yb5i198HrrA_hY4iv.jpg',
    images: [
      '/images/products/0LSLx8yb5i198HrrA_hY4iv.jpg',
      '/images/products/0G650jVmIEfWeXz4E_J3ooX.jpg',
      '/images/products/0XZTh7oEMuM9SShl8_2MsXh.jpg',
      '/images/products/0rvO3qDHq57zOREaB_to7yd.jpg',
      '/images/products/0THRwkPADiGErRSWc_lhBVD.jpg',
      '/images/products/0xi6GLPxjJR8rxAMW_HloKb.jpg',
      '/images/products/0pI0L14yi04UqwTE5_Q6TbA.jpg',
      '/images/products/0rqPgZSMVkLAmizIR_NY3Kr.jpg',
      '/images/products/0lBTwTVYqMBg06V5H_HxZG2.jpg',
      '/images/products/0sHmI3SmtPH7NXMae_j2BPF.jpg',
      '/images/products/0hWu2uhrnELOoJt5o_I3Div.jpg',
      '/images/products/0WDed54BhHY8C4IFE_lOoCu.jpg',
      '/images/products/06Lrt6kdsuPMAoQwg_Te95g.jpg',
      '/images/products/0FVPNUgWvRVDSF44T_TNz1r.jpg',
    ],
    videos: ['/videos/products/Ричмонд__91pct_smaller.mp4', null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },

  // ── Küchen · Modern ──────────────────────────────────────────────
  { name: 'Jazz',          slug: 'jazz',          cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/9de6f037c88b066ce32f61f72361c66a.jpg',
    images: [
      '/images/portfolio/6d1ed694f776e465fa77a1192befa111.jpg',
      '/images/portfolio/9f706c1f18bbff9e2db198992dec3fdf.jpg',
      '/images/portfolio/ff2758d04d24d6ccfbd270f616a44ce4.jpg',
      '/images/portfolio/957902645e29383dd443b08eb1003514.jpg',
      '/images/portfolio/9c9ccc42e8ef3090d5487ab19a787f9f.jpg',
    ] },
  { name: 'Vector',        slug: 'vector',        cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/fed2f3b04a726cae4a580da51a38d397.jpg',
    images: [
      '/images/portfolio/4d6c6784b17e3bafbadd7530f1704127.jpg',
      '/images/portfolio/375ebe2fac66ae94848acbce25dd42f6.jpg',
      '/images/portfolio/25dbb2c9d513f4858a6c1f247e722860.jpg',
    ] },
  { name: 'Vector Touch',  slug: 'vector-touch',  cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/9488f3d942a6ebaf2c8a0112fc545da0.jpg',
    images: [
      '/images/portfolio/ad7cb35eb0c5e2758ea72a5fbdc90622.jpg',
      '/images/portfolio/f66e59ddc921391eb74bb9e2e29db1a7.jpg',
      '/images/portfolio/449496390bcc255dc9a3dbf6ff9d955c.jpg',
      '/images/portfolio/f7922a53629cc62c386441dcc52d21d4.jpg',
      '/images/portfolio/4f0ddcd36ef1dee2d28fef62b0298ebe.jpg',
    ] },
  { name: 'Integrato',     slug: 'integrato',     cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/12ae09b1a6859eb54b400695a28e6a86.jpg',
    images: [
      '/images/portfolio/36344037b995985766eeceef83ce2416.jpg',
      '/images/promo/models/jazz.jpg',
      '/images/promo/models/avenue.jpg',
      '/images/promo/models/nicolle.jpg',
    ] },
  { name: 'Antro Rustic',  slug: 'antro-rustic',  cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/58f1e2b57f8f4ed743ebb87f40626737.jpg',
    images: [
      '/images/portfolio/9b23c597513929daa97cbdef00eb3443.jpg',
      '/images/promo/models/nicolle.jpg',
      '/images/promo/models/jazz.jpg',
    ] },
  { name: 'Antro Stone',   slug: 'antro-stone',   cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/79098b697b42e6831af626abb665935b.jpg',
    images: [
      '/images/portfolio/79098b697b42e6831af626abb665935b.jpg',
      '/images/portfolio/8bab6d0250c5603df2c6e72bbd09c887.jpg',
      '/images/portfolio/5d5000814ce431a30c35f0306128b63e.jpg',
      '/images/portfolio/e8097a2089e2e4a9421766b83da08807.jpg',
      '/images/portfolio/6d6cde067ab07dd9d11e6a6ce2e0110b.jpg',
    ] },
  { name: 'Antro Wood',    slug: 'antro-wood',    cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/e105639a0efa351c4fed8bee07850822.jpg',
    images: [
      '/images/portfolio/89de0ddf7b5b034ac8385a01405d5be4.jpg',
      '/images/portfolio/fae9da93e4160bd01bb7e2feae3394b5.jpg',
      '/images/portfolio/65c6e69e8c1dd6031e37d867cd6b365d.jpg',
      '/images/portfolio/5a898f2ce716f5ce57efbe6482892195.jpg',
      '/images/portfolio/469bc3b1fb2feca02c41b8241374c871.jpg',
      '/images/portfolio/e6fbe2c773de88b394e8415342cebdfc.jpg',
    ] },
  { name: 'Milaro Garden', slug: 'milaro-garden', cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/dcd8e438154a09bf051818beab3324c7.jpg',
    images: [
      '/images/portfolio/dcd8e438154a09bf051818beab3324c7.jpg',
      '/images/portfolio/76b6ebe004f7543fe05a48e9ec1fca25.jpg',
      '/images/portfolio/aa4430af56c15196b7112388987007a2.jpg',
      '/images/portfolio/0c393b0dd0836fd86c9dfb693e5846a3.jpg',
      '/images/portfolio/581647e9f39cc11c1b6ed217e590263c.jpg',
      '/images/portfolio/b43452c492176a3ea329e8b9c78ff2de.jpg',
    ] },
  { name: 'Wood Décor Email', slug: 'wood-dekor-email', cat: 'kuechen', type: 'modern', label: 'Küche', img: '/images/portfolio/9160b6cce5996b30c21c0ee66d9b6ed1.jpg',
    images: [
      '/images/portfolio/9160b6cce5996b30c21c0ee66d9b6ed1.jpg',
      '/images/portfolio/65c52c56114150980c1a65246a9b0a81.jpg',
      '/images/portfolio/52b07953411fc3fed5f8cfb1476fa11d.jpg',
      '/images/portfolio/79331d9e3a19189cb637a3193ee4ec29.jpg',
    ] },
  { name: 'Tokyo Glanz',   slug: 'tokyo-glanz',   cat: 'kuechen', type: 'modern',     label: 'Küche', img: '/images/portfolio/82128da6551c91c84cbb51e5d417a8dd.jpg',
    images: [
      '/images/portfolio/82128da6551c91c84cbb51e5d417a8dd.jpg',
      '/images/portfolio/fa8bbe86059d3b77beef41e70fb2dc10.jpg',
      '/images/portfolio/b53eac58ea68c013c3700ebe3b73e2ce.jpg',
      '/images/portfolio/35408d9a5223b11dfc452846b8e10eda.jpg',
      '/images/portfolio/159df34b49f832891dac5ca8670fe49c.jpg',
    ] },

  // ── Küchen · Klassisch ───────────────────────────────────────────
  { name: 'Avenue',        slug: 'avenue',        cat: 'kuechen', type: 'klassisch',  label: 'Küche', img: '/images/portfolio/732b7f0d5bd7b5dc0051775764936d0c.jpg',
    images: [
      '/images/portfolio/157b7f95f6a486942125610a66b7a16d.jpg',
      '/images/portfolio/a2e60e03ee19eec2cbf755afa55b0825.jpg',
      '/images/portfolio/b18263e322c18dc31a9d84f6309c57af.jpg',
      '/images/portfolio/94bddd27e343b31e6f6e8213027cb8b6.jpg',
      '/images/portfolio/19c29c2caa132698c9513ce6611ad1c4.jpg',
      '/images/portfolio/cdf02abaee32bfcf9a599c2ef38e9e5e.jpg',
    ] },
  { name: 'Teramo',        slug: 'teramo',        cat: 'kuechen', type: 'klassisch',  label: 'Küche', img: '/images/portfolio/e96fd11f98f6a44ff68a99588b6706a2.jpg',
    images: [
      '/images/portfolio/1755375e35b12cce2e43a1c1057c5a32.jpg',
      '/images/portfolio/71505dd846e2bfa02b0c2d2c40966a85.jpg',
      '/images/portfolio/301257cf2756f1ddc2d0807f5de21803.jpg',
      '/images/portfolio/1a81ba48e80618408605908af0f11889.jpg',
      '/images/portfolio/bef45663f6317f0cdf616ec2d04128e2.jpg',
      '/images/portfolio/22dc155826c9807efba513bf9ff41d66.jpg',
    ] },
  { name: 'Vienna',        slug: 'vienna',        cat: 'kuechen', type: 'klassisch',  label: 'Küche', img: '/images/portfolio/a56c9ba692d61e8cfd0b34cbecb0e62e.jpg',
    images: [
      '/images/portfolio/d811f57d6447f88081bff41c44a8d237.jpg',
      '/images/portfolio/db39d5a5976863965de6d8016675a526.jpg',
      '/images/portfolio/860e8313fb189c66164e4f704f32be09.jpg',
      '/images/portfolio/1df656cbc9c4482284bddf5d0aa905a1.jpg',
      '/images/portfolio/c9b1e4498f7de28ec7b8d2687b6e2569.jpg',
    ] },
  { name: 'Trento Email',  slug: 'trento-email',  cat: 'kuechen', type: 'klassisch',  label: 'Küche', img: '/images/promo/models/trento1.jpg',
    images: [
      '/images/portfolio/04ef1124228874234fa06c97604e907d.jpg',
      '/images/portfolio/c28ceeb9c44d970183186d4358a5626c.jpg',
      '/images/portfolio/be647c32e2aef29af493c0168d5eada0.jpg',
      '/images/portfolio/2bd3025ad16fe1d63ba98d475a409958.jpg',
      '/images/portfolio/eedd034d4793f21d5aa1b8ffeea26444.jpg',
    ] },
  { name: 'Nicolle Thermoplast', slug: 'nicolle-thermoplast', cat: 'kuechen', type: 'klassisch', label: 'Küche', img: '/images/portfolio/c355e09042eddd6324b165aad5714e59.jpg',
    images: [
      '/images/portfolio/3969eeed2cce84c478d771a9cdcb8628.jpg',
      '/images/portfolio/259a458b7e1bf6c1a813c3c827ed4e33.jpg',
      '/images/portfolio/57582b228dcc913b5a874633e7954760.jpg',
      '/images/portfolio/166db40ecd6a2f1da4b3da2c5816bdd6.jpg',
      '/images/portfolio/ba9fffca44218b607d6ab45cd30092eb.jpg',
    ] },

  // ── Küchen · Neoklassik ──────────────────────────────────────────
  { name: 'Jazz Allure',   slug: 'jazz-allure',   cat: 'kuechen', type: 'neoklassik', label: 'Küche', img: '/images/portfolio/ff9a710b148730a1d74acffdc6d6c965.jpg',
    images: [
      '/images/portfolio/ff9a710b148730a1d74acffdc6d6c965.jpg',
      '/images/portfolio/a5f9d7491b51db44bdfa567a49c7dc4f.jpg',
      '/images/portfolio/b9e2d0f33da57b71867abb51b90d264f.jpg',
      '/images/portfolio/776bec178a444748e899fc9248b5427f.jpg',
      '/images/portfolio/f974bd58f3c81996eb04225d640c3f53.jpg',
    ] },
  { name: 'Jazz Intuit',   slug: 'jazz-intuit',   cat: 'kuechen', type: 'neoklassik', label: 'Küche', img: '/images/promo/models/jazz3.jpg',
    images: [
      '/images/portfolio/6d1ed694f776e465fa77a1192befa111.jpg',
      '/images/portfolio/9f706c1f18bbff9e2db198992dec3fdf.jpg',
      '/images/portfolio/ff2758d04d24d6ccfbd270f616a44ce4.jpg',
      '/images/portfolio/957902645e29383dd443b08eb1003514.jpg',
      '/images/portfolio/9c9ccc42e8ef3090d5487ab19a787f9f.jpg',
    ] },
  { name: 'Jazz Kabinet',  slug: 'jazz-kabinet',  cat: 'kuechen', type: 'neoklassik', label: 'Küche', img: '/images/promo/models/mix2.jpg',
    images: [
      '/images/portfolio/f296dd17f9b554063edfd1831217f10f.jpg',
      '/images/portfolio/dfc8ab70d360e72a6c6d68cf3fd9d66f.jpg',
      '/images/portfolio/db53c589c2c71edf9c15cff02095a649.jpg',
    ] },
  { name: 'Mix 22',        slug: 'mix-22',        cat: 'kuechen', type: 'neoklassik', label: 'Küche', img: '/images/portfolio/f1b9acb5375bb806e0cd4a90ebb0eb2f.jpg',
    images: [
      '/images/portfolio/1c736d98b62f694f8227ff4348dc5618.jpg',
      '/images/portfolio/7b89b06eaece34af91fc32a7cf4ce7da.jpg',
      '/images/portfolio/ac72773fd5a85c35b7fb482766412d88.jpg',
    ] },

  // ── Schränke · Drehtüren ─────────────────────────────────────────
  { name: 'Nicolle Schrank',       slug: 'nicolle-cabinet',        cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/nicolle-cabinet/01.jpg', images: ['/images/schraenke/nicolle-cabinet/01.jpg','/images/schraenke/nicolle-cabinet/02.jpg','/images/schraenke/nicolle-cabinet/03.jpg','/images/schraenke/nicolle-cabinet/04.jpg','/images/schraenke/nicolle-cabinet/05.jpg','/images/schraenke/nicolle-cabinet/06.jpg'] },
{ name: 'Mixal Schrank',       slug: 'mixal-cabinet',      cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/mixal-cabinet/01.jpg',  images: ['/images/schraenke/mixal-cabinet/01.jpg','/images/schraenke/mixal-cabinet/02.jpg','/images/schraenke/mixal-cabinet/03.jpg'] },
  { name: 'Spark Schrank',       slug: 'spark-cabinet',      cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/spark-cabinet/01.jpg',  images: ['/images/schraenke/spark-cabinet/01.jpg','/images/schraenke/spark-cabinet/02.jpg','/images/schraenke/spark-cabinet/03.jpg','/images/schraenke/spark-cabinet/04.jpg'] },
  { name: 'Teramo Schrank',     slug: 'teramo-cabinet',     cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/teramo-cabinet/01.jpg', images: ['/images/schraenke/teramo-cabinet/01.jpg','/images/schraenke/teramo-cabinet/02.jpg','/images/schraenke/teramo-cabinet/03.jpg','/images/schraenke/teramo-cabinet/04.jpg','/images/schraenke/teramo-cabinet/05.jpg'] },
  { name: 'Mix 22 Schrank',     slug: 'mix-cabinet',        cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/mix-cabinet/01.jpg', images: ['/images/schraenke/mix-cabinet/01.jpg','/images/schraenke/mix-cabinet/02.jpg','/images/schraenke/mix-cabinet/03.jpg','/images/schraenke/mix-cabinet/04.jpg'] },
  { name: 'Vector Schrank',     slug: 'vector-cabinet',     cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/vector-cabinet/01.jpg', images: ['/images/schraenke/vector-cabinet/01.jpg','/images/schraenke/vector-cabinet/02.jpg','/images/schraenke/vector-cabinet/03.jpg'] },
  { name: 'Jazz Schrank',       slug: 'jazz-cabinet',       cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/jazz-cabinet/01.jpg', images: ['/images/schraenke/jazz-cabinet/01.jpg','/images/schraenke/jazz-cabinet/02.jpg','/images/schraenke/jazz-cabinet/03.jpg','/images/schraenke/jazz-cabinet/04.jpg'] },
  { name: 'Ice Schrank',        slug: 'ice-cabinet',        cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/ice-cabinet/01.jpg', images: ['/images/schraenke/ice-cabinet/01.jpg','/images/schraenke/ice-cabinet/02.jpg','/images/schraenke/ice-cabinet/03.jpg'] },
  { name: 'Integrato Schrank',  slug: 'integrato-cabinet',  cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/integrato-cabinet/01.jpg', images: ['/images/schraenke/integrato-cabinet/01.jpg','/images/schraenke/integrato-cabinet/02.jpg','/images/schraenke/integrato-cabinet/03.jpg','/images/schraenke/integrato-cabinet/04.jpg','/images/schraenke/integrato-cabinet/05.jpg'] },
  { name: 'Kamelie Schrank',     slug: 'camelia-cabinet',    cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/camelia-cabinet/01.jpg', images: ['/images/schraenke/camelia-cabinet/01.jpg','/images/schraenke/camelia-cabinet/02.jpg','/images/schraenke/camelia-cabinet/03.jpg','/images/schraenke/camelia-cabinet/04.jpg','/images/schraenke/camelia-cabinet/05.jpg'] },
  { name: 'Antro Schrank',       slug: 'antro-cabinet',      cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/antro-cabinet/01.jpg', images: ['/images/schraenke/antro-cabinet/01.jpg','/images/schraenke/antro-cabinet/02.jpg','/images/schraenke/antro-cabinet/03.jpg','/images/schraenke/antro-cabinet/04.jpg','/images/schraenke/antro-cabinet/05.jpg','/images/schraenke/antro-cabinet/06.jpg','/images/schraenke/antro-cabinet/07.jpg'] },
  { name: 'Trento Schrank',      slug: 'trento-cabinet',     cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/trento-cabinet/01.jpg', images: ['/images/schraenke/trento-cabinet/01.jpg','/images/schraenke/trento-cabinet/02.jpg','/images/schraenke/trento-cabinet/03.jpg'] },
  { name: 'Jazz Allure Schrank',   slug: 'allure-cabinet',         cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/allure-cabinet/01.jpg', images: ['/images/schraenke/allure-cabinet/01.jpg','/images/schraenke/allure-cabinet/02.jpg','/images/schraenke/allure-cabinet/03.jpg'] },
  { name: 'Tokyo Schrank',         slug: 'tokyo-cabinet',          cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/tokyo-cabinet/01.jpg', images: ['/images/schraenke/tokyo-cabinet/01.jpg','/images/schraenke/tokyo-cabinet/02.jpg','/images/schraenke/tokyo-cabinet/03.jpg'] },
  { name: 'Tokyo Glanz Schrank',   slug: 'tokyo-glyanets-cabinet', cat: 'schraenke', type: 'drehtueren',     label: 'Drehtürenschrank', img: '/images/schraenke/tokyo-glyanets-cabinet/01.jpg', images: ['/images/schraenke/tokyo-glyanets-cabinet/01.jpg','/images/schraenke/tokyo-glyanets-cabinet/02.jpg','/images/schraenke/tokyo-glyanets-cabinet/03.jpg','/images/schraenke/tokyo-glyanets-cabinet/04.jpg'] },

  // ── Schränke · Schiebetüren ──────────────────────────────────────
  { name: 'Mix 22 Schiebetüren',   slug: 'mix-wardrobe',       cat: 'schraenke', type: 'schiebetuer',    label: 'Schiebetürenschrank', img: '/images/schraenke/mix-wardrobe/01.jpg', images: ['/images/schraenke/mix-wardrobe/01.jpg','/images/schraenke/mix-wardrobe/02.jpg','/images/schraenke/mix-wardrobe/03.jpg','/images/schraenke/mix-wardrobe/04.jpg'] },


  // ── Schränke · Ankleidezimmer ────────────────────────────────────
  { name: 'Optima Ankleidezimmer', slug: 'optima-dressing', cat: 'schraenke', type: 'ankleidezimmer', label: 'Ankleidezimmer', img: '/images/schraenke/optima-dressing/01.jpg', images: ['/images/schraenke/optima-dressing/01.jpg','/images/schraenke/optima-dressing/02.jpg','/images/schraenke/optima-dressing/03.jpg'] },
  { name: 'Stilos Ankleidezimmer', slug: 'stilos',          cat: 'schraenke', type: 'ankleidezimmer', label: 'Ankleidezimmer', img: '/images/schraenke/stilos/01.jpg', images: ['/images/schraenke/stilos/01.jpg','/images/schraenke/stilos/02.jpg','/images/schraenke/stilos/03.jpg'] },

  // ── Bäder ───────────────────────────────────────────────
  { name: 'Nicole Badezimmer',      slug: 'nicolle-bathroom',  cat: 'baeder', type: 'klassisch',  label: 'Badezimmer', img: '/images/baeder/nicolle-bathroom/01.jpg', images: ['/images/baeder/nicolle-bathroom/01.jpg','/images/baeder/nicolle-bathroom/02.jpg','/images/baeder/nicolle-bathroom/03.jpg','/images/baeder/nicolle-bathroom/04.jpg','/images/baeder/nicolle-bathroom/05.jpg','/images/baeder/nicolle-bathroom/06.jpg'] },
  { name: 'Trento Badezimmer',      slug: 'trento-bathroom',   cat: 'baeder', type: 'klassisch',  label: 'Badezimmer', img: '/images/baeder/trento-bathroom/01.jpg', images: ['/images/baeder/trento-bathroom/01.jpg','/images/baeder/trento-bathroom/02.jpg','/images/baeder/trento-bathroom/03.jpg','/images/baeder/trento-bathroom/04.jpg','/images/baeder/trento-bathroom/05.jpg','/images/baeder/trento-bathroom/06.jpg'] },
  { name: 'Kamelie Badezimmer',     slug: 'camelia-bathroom',  cat: 'baeder', type: 'klassisch',  label: 'Badezimmer', img: '/images/baeder/camelia-bathroom/01.jpg', images: ['/images/baeder/camelia-bathroom/01.jpg','/images/baeder/camelia-bathroom/02.jpg','/images/baeder/camelia-bathroom/03.jpg','/images/baeder/camelia-bathroom/04.jpg','/images/baeder/camelia-bathroom/05.jpg','/images/baeder/camelia-bathroom/06.jpg'] },
  { name: 'Mix 22 Badezimmer',      slug: 'mix-22-bathroom',   cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/mix-22-bathroom/01.jpg', images: ['/images/baeder/mix-22-bathroom/01.jpg','/images/baeder/mix-22-bathroom/02.jpg','/images/baeder/mix-22-bathroom/03.jpg','/images/baeder/mix-22-bathroom/04.jpg','/images/baeder/mix-22-bathroom/05.jpg','/images/baeder/mix-22-bathroom/06.jpg'] },
  { name: 'Spark Badezimmer',        slug: 'spark-bathroom',    cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/spark-bathroom/01.jpg', images: ['/images/baeder/spark-bathroom/01.jpg','/images/baeder/spark-bathroom/02.jpg','/images/baeder/spark-bathroom/03.jpg','/images/baeder/spark-bathroom/04.jpg','/images/baeder/spark-bathroom/05.jpg','/images/baeder/spark-bathroom/06.jpg','/images/baeder/spark-bathroom/07.jpg','/images/baeder/spark-bathroom/08.jpg','/images/baeder/spark-bathroom/09.jpg','/images/baeder/spark-bathroom/10.jpg','/images/baeder/spark-bathroom/11.jpg','/images/baeder/spark-bathroom/12.jpg'] },
  { name: 'Vector Badezimmer',       slug: 'vector-bathroom',   cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/vector-bathroom/01.jpg', images: ['/images/baeder/vector-bathroom/01.jpg','/images/baeder/vector-bathroom/02.jpg'] },
  { name: 'Jazz Badezimmer',         slug: 'jazz-bathroom',     cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/jazz-bathroom/01.jpg', images: ['/images/baeder/jazz-bathroom/01.jpg','/images/baeder/jazz-bathroom/02.jpg','/images/baeder/jazz-bathroom/03.jpg'] },
  { name: 'Tokyo Badezimmer',        slug: 'tokyo-bathroom',    cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/tokyo-bathroom/01.jpg', images: ['/images/baeder/tokyo-bathroom/01.jpg','/images/baeder/tokyo-bathroom/02.jpg','/images/baeder/tokyo-bathroom/03.jpg','/images/baeder/tokyo-bathroom/04.jpg'] },
  { name: 'Teramo Badezimmer',       slug: 'teramo-bathroom',   cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/teramo-bathroom/01.jpg', images: ['/images/baeder/teramo-bathroom/01.jpg','/images/baeder/teramo-bathroom/02.jpg','/images/baeder/teramo-bathroom/03.jpg','/images/baeder/teramo-bathroom/04.jpg','/images/baeder/teramo-bathroom/05.jpg'] },
  { name: 'Urbano Badezimmer',       slug: 'urbano-bathroom',   cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/urbano-bathroom/01.jpg', images: ['/images/baeder/urbano-bathroom/01.jpg','/images/baeder/urbano-bathroom/02.jpg','/images/baeder/urbano-bathroom/03.jpg'] },
  { name: 'Sole Badezimmer',         slug: 'sole-bathroom',     cat: 'baeder', type: 'modern',     label: 'Badezimmer', img: '/images/baeder/sole-bathroom/01.jpg', images: ['/images/baeder/sole-bathroom/01.jpg','/images/baeder/sole-bathroom/02.jpg','/images/baeder/sole-bathroom/03.jpg','/images/baeder/sole-bathroom/04.jpg','/images/baeder/sole-bathroom/05.jpg','/images/baeder/sole-bathroom/06.jpg'] },
]
